const projects = [
  {
    name: "TabSense - Intelligent Browser Tab Knowledge Graph",
    image: "/ProjectImages/tabsense.jpg",
    technologies: ["Python", "FastAPI", "NLP", "Transformers", "NetworkX", "REST APIs"],
    description: "Built FastAPI-based backend platform transforming browser tabs into structured knowledge graphs. Developed REST APIs and NLP-powered processing pipelines with summarization, entity extraction, semantic search, and relationship discovery. Implemented transformer-based embeddings and graph-based data models. Solved data consistency and scalability challenges.",
    github: "https://github.com/ThisIsSurabhiSinha/TabSense",
    deployed: "",
    category: ["Backend"],
  },
  {
    name: "Club Catalyst",
    image: "/ProjectImages/ClubManagement.png",
    technologies: ["Python", "Django", "JavaScript", "HTML", "CSS", "Bootstrap", "REST APIs", "SQLite"],
    description: "Comprehensive college club management platform with role-based authentication (administrators, club members, general users). Features include announcements, communication workflows, messaging, discussion forums, and event management. Designed relational database schemas using Django ORM. Optimized API endpoints for better performance.",
    github: "https://github.com/ThisIsSurabhiSinha/ClubManagement",
    deployed: "https://clubcatalyst-y67f5eu3.b4a.run/",
    category: ["Backend", "Fullstack"],
  },
  {
    name: "Portfolio Website",
    image: "/ProjectImages/Portfolio.png",
    technologies: ["Html", "ReactJS", "CSS", "JavaScript", "Bootstrap"],
    description: "A personal portfolio website to showcase my projects and skills.",
    github: "https://github.com/ThisIsSurabhiSinha/portfolio",
    deployed: "https://portfolio-xi-lac-98.vercel.app/",
    category: ["Frontend"],
  },
  {
    name: "Pizza App",
    image: "/ProjectImages/PizzaApp.png",
    technologies: ["Html", "CSS", "JavaScript", "Django", "Bootstrap", "REST APIs", "JQuery"],
    description: "A pizza ordering platform with order tracking and history.",
    github: "https://github.com/ThisIsSurabhiSinha/PizzaApp",
    deployed: "https://pizzaroo-pizza-delivery-app.onrender.com",
    category: ["Fullstack" , "Backend"],
  },
  {
    name: "Tic Tac Toe",
    image: "/ProjectImages/TicTacToe.jpg",
    technologies: ["Html", "CSS", "JavaScript", "Bootstrap"],
    description: "A simple Tic Tac Toe game built using frontend technologies.",
    github: "https://github.com/ThisIsSurabhiSinha/TicTacToe",
    deployed: "https://thisissurabhisinha.github.io/TicTacToe/",
    category: ["Frontend"],
  },
  {
    name: "Tenzie Game",
    image: "/ProjectImages/TenzieGame.jpg",
    technologies: ["Html", "ReactJS", "CSS", "JavaScript", "Bootstrap"],
    description: "A fun dice game built using React.",
    github: "https://github.com/ThisIsSurabhiSinha/tenzie-game",
    deployed: "https://tenzie-game-sage.vercel.app/",
    category: ["Frontend"],
  },
  {
    name: "Assembly Endgame",
    image: "/ProjectImages/AssemblyEndgame.jpg",
    technologies: ["Html", "ReactJS", "CSS", "JavaScript", "Bootstrap"],
    description: "A React-based project showcasing advanced assembly features.",
    github: "https://github.com/ThisIsSurabhiSinha/assembly-endgame",
    deployed: "https://assembly-endgame.vercel.app/",
    category: ["Frontend"],
  },
  {
    name: "Meme Blast",
    image: "/ProjectImages/MemeBlast.jpg",
    technologies: ["Html", "ReactJS", "CSS", "JavaScript", "Bootstrap"],
    description: "A fun app for browsing and sharing memes.",
    github: "https://github.com/ThisIsSurabhiSinha/memeBlast",
    deployed: "https://meme-blast-eight.vercel.app/",
    category: ["Frontend"],
  },
  {
    name: "My Business Card",
    image: "/ProjectImages/BusinessCard.jpg",
    technologies: ["Html", "ReactJS", "CSS", "JavaScript", "Bootstrap"],
    description: "A professional business card app built using React.",
    github: "https://github.com/ThisIsSurabhiSinha/Business-Card",
    deployed: "https://business-card-zyvp.vercel.app/",
    category: ["Frontend"],
  },
  {
    name: "ListEase - ToDo List",
    image: "/ProjectImages/toDoList.jpg",
    technologies: ["Html", "CSS", "JavaScript"],
    description: "A task management application for organizing and tracking todos.",
    github: "https://github.com/ThisIsSurabhiSinha/ToDo",
    deployed: "https://thisissurabhisinha.github.io/ToDo/",
    category: ["Frontend"],
  },
];

export default projects;
