
const projects = [
    {
      name: "Portfolio Website",
      image: "../assests/placeholder.jpeg", 
      technologies: "Html, React, CSS, JavaScript , ",
      description: "A personal portfolio website to showcase my projects and skill",
      deployed: "https://your-portfolio-link.com",
      category: "Frontend",
    },
    {
      name: "Pizza App",
      image: "../assests/placeholder.jpeg", 
      technologies: "Html, CSS, Javascript, Django, Bootstrap, REST APIs, Jquery, ",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Fullstack",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/your-username/pizza-app",
      deployed: "https://your-pizza-app-link.com",
      category: "Frontend",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Backend",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Frontend",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Fullstack",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Fullstack",
    },
  
    {
      name: "Tic Tac Toe",
      image: "../assests/placeholder.jpeg", 
      technologies: "Django, Bootstrap, REST APIs",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Backend",
    },
  ];

  export default projects;