
const projects = [
    {
      name: "Portfolio Website",
      image: "../assests/ProjectImages/Portfolio.png", 
      technologies: "Html, ReactJS, CSS, JavaScript , Bootstrap",
      description: "A personal portfolio website to showcase my projects and skill",
      deployed: "https://your-portfolio-link.com",
      category: "Frontend",
    },
    {
      name: "Pizza App",
      image: "../assests/ProjectImages/placeholder.jpeg", 
      technologies: "Html, CSS, Javascript, Django, Bootstrap, REST APIs, Jquery, ",
      description: "A pizza ordering platform with order tracking and history.",
      github: "../assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Fullstack",
    },
    {
      name: "Tic Tac Toe",
      image: "../assests/ProjectImages/placeholder.jpeg", 
      technologies: "Html, CSS, JavaScript , Bootstrap",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/your-username/pizza-app",
      deployed: "https://your-pizza-app-link.com",
      category: "Frontend",
    },
    {
      name: "Tenzie Game",
      image: "../assests/ProjectImages/placeholder.jpeg", 
      technologies: "Html, ReactJS, CSS, JavaScript , Bootstrap",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/ThisIsSurabhiSinha/tenzie-game",
      deployed: "https://tenzie-game-sage.vercel.app/",
      category: "Frontend",
    },
    {
      name: "Assembly Endgame",
      image: "../assests/ProjectImages/AssemblyEndgame.jpg", 
      technologies: "Html, ReactJS, CSS, JavaScript , Bootstrap",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/ThisIsSurabhiSinha/assembly-endgame",
      deployed: "https://assembly-endgame.vercel.app/",
      category: "Frontend",
    },
    {
      name: "Meme Blast",
      image: "../assests/ProjectImages/MemeBlast.jpg", 
      technologies: "Html, ReactJS, CSS, JavaScript , Bootstrap",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/ThisIsSurabhiSinha/memeBlast",
      deployed: "https://meme-blast-eight.vercel.app/",
      category: "Frontend",
    },
    {
      name: "My Business Card",
      image:"BusinessCard", 
      technologies: "Html, ReactJS, CSS, JavaScript , Bootstrap",
      description: "A pizza ordering platform with order tracking and history.",
      github: "https://github.com/ThisIsSurabhiSinha/Business-Card",
      deployed: "https://business-card-zyvp.vercel.app/",
      category: "Fullstack",
    },
  
    {
      name: "Club Catalyst",
      image: "../assests/ProjectImages/placeholder.jpeg", 
      technologies: "Html, CSS, Javascript, Django, Bootstrap, REST APIs, Jquery, ",
      description: "Club Catalyst is a comprehensive platform designed to manage and streamline club activities within our college. The website facilitates event scheduling, member management, task assignments, and communication, making club operations more efficient and organized.",
      github: "assests/placeholder.jpeg",
      deployed: "https://your-pizza-app-link.com",
      category: "Backend",
    },
  ];

  export default projects;